version: '3'
services:
  frontend:
    build:
      context: ./portfolio-website
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    ports:
      - "8000:8000"